export const copy = {
  en: {
    signIn: "Sign in to upload", signOut: "Sign out", accountIntro: "Use your 6thSense contributor account.", phone: "Phone number", phoneHint: "Include your country code. For Korea, use +82 and omit the first 0.", password: "Password", working: "Please wait…", forgotPassword: "Forgot password?", resetPassword: "Reset password", backToSignIn: "Back to sign in", newPassword: "New password", passwordHint: "At least 12 characters, including uppercase, lowercase and a number.", code: "Verification code", sendCode: "Send reset code", codeSent: "Enter the verification code sent to your registered phone.", passwordChanged: "Password updated. You can now sign in.", noAccount: "New contributor? Complete onboarding with 6thSense to activate your account and camera.",
    errors: {
      phone_format: "Enter a phone number with its country code, for example +821012345678.",
      NotAuthorizedException: "Check your phone number and password, then sign in again.", UserNotFoundException: "Check your phone number and password, then sign in again.",
      UserNotConfirmedException: "Your phone verification is not complete. Contact 6thSense to finish onboarding.", PasswordResetRequiredException: "Please reset your password before signing in.",
      TooManyRequestsException: "Too many attempts. Please wait a moment and try again.", LimitExceededException: "Too many attempts. Please wait and try again later.",
      CodeMismatchException: "The verification code does not match. Try again.", ExpiredCodeException: "The code expired. Request a new reset code.", InvalidPasswordException: "Use at least 12 characters with uppercase, lowercase and a number.",
      sign_in_unavailable: "Sign-in is temporarily unavailable. Please retry or contact 6thSense.", account_setup_required: "Contact 6thSense to finish setting up your contributor account.", authentication_required: "Your session ended. Sign in again to resume.",
      enrollment_required: "Your account still needs to be linked to your contributor profile. Contact 6thSense.", enrollment_inactive: "Your contributor profile is not active. Contact 6thSense.",
      consent_required: "Your participation agreements need to be completed or updated before uploading. Contact 6thSense.", camera_approval_required: "Your camera assignment is waiting for approval. Contact 6thSense.",
      verified_account_required: "Verify your phone and complete contributor onboarding before uploading.", account_deletion_pending: "This account has a deletion request and cannot accept uploads.", signout_retry: "You are signed out on this device. We could not confirm server sign-out; contact 6thSense if this device was shared.",
    },
    title: "Upload your episodes.", eyebrow: "CONTRIBUTOR UPLOADS", intro: "Send your original episode folders to 6thSense for review.",
    loading: "Checking your account…", for: "Signed in as", private: "Uploads are linked to your signed-in contributor account.",
    drop: "Drop episode folders here", choose: "Choose folders", hint: "Choose an episode folder, or a parent folder containing several episodes.",
    original: "Keep the original folder names and include metadata.json, video and sensor files.",
    heading: "Before you upload", steps: ["Stop recording and connect your SD card to your computer.", "Select the whole episode folder, not just the video.", "Keep this tab open. If interrupted, select the same folders to resume."],
    queue: "Your episodes", empty: "No episodes selected yet", start: "Upload episodes", resume: "Resume upload", pause: "Pause", clear: "Clear selection",
    ready: "Ready", preparing: "Preparing…", uploading: "Uploading…", paused: "Paused", failed: "Needs attention", complete: "Received", checking: "Reading folders…",
    received: "Episodes received. Thank you.", next: "6thSense will review your recordings. Upload completion does not mean footage has been accepted for payment.",
    files: "files", ignored: "unrelated or hidden files skipped", history: "Recent deliveries", incomplete: "Select the same folders to continue", contact: "Need a hand?",
    remove: "Remove", allowance: "Available within 24 hours", noData: "Only original recording folders are accepted.",
  },
  ko: {
    signIn: "로그인하고 업로드", signOut: "로그아웃", accountIntro: "6thSense 참여자 계정으로 로그인해 주세요.", phone: "전화번호", phoneHint: "국가번호를 포함해 주세요. 한국 번호는 맨 앞 0을 빼고 +82로 시작합니다.", password: "비밀번호", working: "잠시만 기다려 주세요…", forgotPassword: "비밀번호를 잊으셨나요?", resetPassword: "비밀번호 재설정", backToSignIn: "로그인으로 돌아가기", newPassword: "새 비밀번호", passwordHint: "대문자, 소문자, 숫자를 포함하여 12자 이상 입력해 주세요.", code: "인증번호", sendCode: "재설정 인증번호 받기", codeSent: "등록한 전화번호로 받은 인증번호를 입력해 주세요.", passwordChanged: "비밀번호가 변경되었습니다. 다시 로그인해 주세요.", noAccount: "처음 참여하시나요? 6thSense와 온보딩을 완료한 뒤 계정과 카메라를 활성화할 수 있습니다.",
    errors: {
      phone_format: "국가번호를 포함한 전화번호를 입력해 주세요. 예: +821012345678",
      NotAuthorizedException: "전화번호와 비밀번호를 확인한 뒤 다시 로그인해 주세요.", UserNotFoundException: "전화번호와 비밀번호를 확인한 뒤 다시 로그인해 주세요.",
      UserNotConfirmedException: "전화번호 인증이 완료되지 않았습니다. 6thSense에 문의해 주세요.", PasswordResetRequiredException: "로그인 전에 비밀번호를 재설정해 주세요.",
      TooManyRequestsException: "시도 횟수가 많습니다. 잠시 후 다시 시도해 주세요.", LimitExceededException: "시도 횟수가 많습니다. 나중에 다시 시도해 주세요.",
      CodeMismatchException: "인증번호가 일치하지 않습니다. 다시 확인해 주세요.", ExpiredCodeException: "인증번호가 만료되었습니다. 새 인증번호를 요청해 주세요.", InvalidPasswordException: "대문자, 소문자, 숫자를 포함하여 12자 이상 입력해 주세요.",
      sign_in_unavailable: "현재 로그인할 수 없습니다. 다시 시도하거나 6thSense에 문의해 주세요.", account_setup_required: "참여자 계정 설정을 완료하려면 6thSense에 문의해 주세요.", authentication_required: "로그인이 만료되었습니다. 다시 로그인하면 이어서 업로드할 수 있습니다.",
      enrollment_required: "계정을 참여자 프로필에 연결해야 합니다. 6thSense에 문의해 주세요.", enrollment_inactive: "참여자 프로필이 비활성 상태입니다. 6thSense에 문의해 주세요.",
      consent_required: "업로드 전에 참여 동의서를 작성하거나 갱신해야 합니다. 6thSense에 문의해 주세요.", camera_approval_required: "카메라 배정 승인을 기다리고 있습니다. 6thSense에 문의해 주세요.",
      verified_account_required: "전화번호 인증과 참여자 온보딩을 완료한 후 업로드해 주세요.", account_deletion_pending: "계정 삭제가 요청되어 업로드할 수 없습니다.", signout_retry: "이 기기에서 로그아웃되었습니다. 서버 로그아웃은 확인되지 않았습니다. 공용 기기라면 6thSense에 문의해 주세요.",
    },
    title: "촬영한 작업을 보내 주세요.", eyebrow: "참여자 업로드", intro: "원본 에피소드 폴더를 6thSense에 전달해 주세요. 이후 검토는 저희가 진행합니다.",
    loading: "참여자 계정을 확인하고 있습니다…", for: "로그인한 참여자", private: "업로드 내역은 로그인한 참여자 계정에 연결됩니다.",
    drop: "에피소드 폴더를 여기에 놓으세요", choose: "폴더 선택", hint: "에피소드 폴더 하나 또는 여러 에피소드가 들어 있는 상위 폴더를 선택하세요.",
    original: "원래 폴더 이름을 유지하고 metadata.json, 영상과 센서 파일을 모두 포함해 주세요.",
    heading: "업로드 전 확인", steps: ["촬영을 종료하고 SD 카드를 컴퓨터에 연결하세요.", "영상 파일만이 아닌 에피소드 폴더 전체를 선택하세요.", "이 탭을 열어 두세요. 중단되면 같은 폴더를 선택해 이어서 업로드할 수 있습니다."],
    queue: "선택한 에피소드", empty: "아직 선택한 에피소드가 없습니다", start: "에피소드 업로드", resume: "이어서 업로드", pause: "일시 정지", clear: "선택 지우기",
    ready: "준비됨", preparing: "준비 중…", uploading: "업로드 중…", paused: "일시 정지됨", failed: "확인이 필요합니다", complete: "접수 완료", checking: "폴더를 읽고 있습니다…",
    received: "에피소드가 접수되었습니다. 감사합니다.", next: "6thSense에서 촬영 내용을 검토합니다. 업로드 완료가 지급 대상 영상으로 승인되었음을 의미하지는 않습니다.",
    files: "개 파일", ignored: "개의 관련 없는 파일 또는 숨김 파일을 제외했습니다", history: "최근 전달 내역", incomplete: "같은 폴더를 선택하면 이어서 진행할 수 있습니다", contact: "도움이 필요하신가요?",
    remove: "제거", allowance: "24시간 기준 남은 업로드 용량", noData: "원본 촬영 폴더만 업로드할 수 있습니다.",
  },
};
